language: python
python:
  - "3.5"

env:
  matrix:
    - MAGENTO_VERSION="1.4.2.0"
    - MAGENTO_VERSION="1.5.1.0"
    - MAGENTO_VERSION="1.6.2.0"
    - MAGENTO_VERSION="1.7.0.2"
    - MAGENTO_VERSION="1.8.1.0"
    - MAGENTO_VERSION="1.9.2.1"
    - MAGENTO_VERSION="1.9.2.4"
    - MAGENTO_VERSION="1.9.3.1"

matrix:
  fast_finish: true

before_install:
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/yara_3.4.0+dfsg-2build1_amd64.deb
  # does not work, get's installed globally, not accessible to Travis venv
  # - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/python-yara_3.4.0+dfsg-2build1_amd64.deb
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/libyara3_3.4.0+dfsg-2build1_amd64.deb
  - sudo dpkg -i *3.4.0*.deb

before_script:
  - bash tools/travis/prepare_magento.sh

script:
  - pip install yara-python
  - nosetests -v mwscan
  - python tools/validate_signatures.py
  - bash tools/travis/test_magento.sh

