language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"

before_install:
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/yara_3.4.0+dfsg-2build1_amd64.deb
  # does not work, get's installed globally, not accessible to Travis venv
  # - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/python-yara_3.4.0+dfsg-2build1_amd64.deb
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/libyara3_3.4.0+dfsg-2build1_amd64.deb
  - sudo dpkg -i *3.4.0*.deb

script:
  - pip install yara-python requests-cache
  - PYTHONPATH=mwscan nosetests -v mwscan/tests/test_mwscan.py
  - python tools/validate_signatures.py

  # This will only run under Py3 and when the rules have changed
  - bash tools/travis_test_magento_releases.sh

