language: python
python:
  - "3.5"
before_install:
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/yara_3.5.0+dfsg-2~precise1_amd64.deb
  - sudo dpkg -i yara_3.5.0+dfsg-2~precise1_amd64.deb
script: python tools/runtests.py
